### ISSUE TITLE
Running a process model without selecting at least one continous predictor fails 

### ISSUE THREAD

**Issue by ThijsVroegh** [nlesc-jasp-projects/jaspProcess#36]
Running a process model with only categorical predictors only works when at leat one continuous predictor is selected (though not used in the model) in the upper main box.

**Comment by ThijsVroegh** [comment]
I got the problem in the version where the 'n' was inflated; for me, everything now also works fine after the latest pull of add-tests

**Comment by maltelueken** [comment]
Ok, good! I will close this then.
